[package]
name = "phroxy"
version = "0.1.0"
authors = ["dvkt <c@dvkt.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.7.1"
phetch = "0.1.10"
htmlescape = "0.3.1"